name: Unzip and Deploy
on:
  push:
    paths:
      - 'repo.zip' # Kích hoạt khi file zip thay đổi

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip files
        run: |
          unzip -o repo.zip -d .
          rm repo.zip # Xóa file zip sau khi giải nén
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto unzip files [skip ci]" || echo "No changes"
          git push
